spring:
  application:
      name: healthcare_enrollee_service
  profiles:
      active: "dev"
  main:
      banner-mode: "off"

server:
  port: 8000

eureka:
  client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka
          instance:
          preferIpAddress: true

---

spring:
  profiles: dev

  datasource:
      url: jdbc:hsqldb:hsql://localhost:8701/healthcare
      username: sa
      password:

  jpa:
      hibernate:
          ddl-auto: update

---

spring:
  profiles: test

  datasource:
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
